[project]
name = "lyricscribe"
version = "1.0.0.dev1"
description = "Converting music to lyrics"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-whisper>=20240930",
]

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
