[project]
name = "lyricscribe"
version = "1.0.0"
description = "Tooling for ALT research."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer",
    "demucs-next @ git+https://github.com/Ryan5453/demucs-next.git",
    "datasets>=3.0",
    "pydantic",
    "transformers",
    "nemo_toolkit[asr]",
    "lhotse>=1.32",
    "antlr4-python3-runtime==4.9.3",
    "silero-vad",
    "jiwer",
    "matplotlib",
    "pandas",
    "torch==2.10.0", # FUCK CUDA
    "torchaudio==2.10.0",
    "torchcodec==0.10.0",
]

[project.scripts]
lyricscribe = "lyricscribe.cli.main:cli"

[build-system]
requires = ["uv_build>=0.7.19,<0.8"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "lyricscribe"
module-root = ""

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]

[tool.uv]
package = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }

[tool.ruff]
lint.extend-select = ["I"]
